# Generated by Django 5.0.7 on 2025-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_section_lesson_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=20),
        ),
    ]
