# Generated by Django 5.0.7 on 2026-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0005_lesson_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasepair",
            name="last_reviewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phrasepair",
            name="next_review",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phrasepair",
            name="review_stage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
