version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: bash -c "mysqladmin ping -h localhost -u root -p$DB_ROOT_PASSWORD"
      interval: 10s
      retries: 5
      start_period: 20s

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: learning-platform
    command: ./django-setup.sh
    volumes:
      - ./backend:/code
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=production
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  mysql-data:
