services:
  web:
    container_name: learning-platform
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["/bin/bash", "-c", "/code/django-setup.sh && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=15883
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend:/code
    env_file:
      - .env
    restart: always
