services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  web:
    container_name: learning-platform
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ./django-setup.sh
    volumes:
      - ./backend:/code
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local
