# Generated by Django 5.0.7 on 2025-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
