# Generated by Django 5.0.7 on 2026-03-11 22:05

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                validators=[user.models.validate_file_size],
            ),
        ),
    ]
