# Generated by Django 5.0.7 on 2026-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_active",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="streak",
            field=models.IntegerField(default=0),
        ),
    ]
