name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd django-docker
            git pull origin main
            docker compose down
            docker compose up -d --build